// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxcHLn98_ArfMWGvin6Bm6u9Rn2BYsQeE',
    appId: '1:90922324784:web:18e63becaa6020d3832ef5',
    messagingSenderId: '90922324784',
    projectId: 'tubes-apb-a8acc',
    authDomain: 'tubes-apb-a8acc.firebaseapp.com',
    storageBucket: 'tubes-apb-a8acc.appspot.com',
    measurementId: 'G-6GNZVZ1NBE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT13jcWekuPINhEs2sH-mZgVASoeiwwsM',
    appId: '1:90922324784:android:0edfa3ebd1c4712c832ef5',
    messagingSenderId: '90922324784',
    projectId: 'tubes-apb-a8acc',
    storageBucket: 'tubes-apb-a8acc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKArCg84SQqyZm9SY1OtmnhJpg23yyKDI',
    appId: '1:90922324784:ios:a5cda99803371eef832ef5',
    messagingSenderId: '90922324784',
    projectId: 'tubes-apb-a8acc',
    storageBucket: 'tubes-apb-a8acc.appspot.com',
    iosClientId: '90922324784-n1eo7eulgh6qvbspuj83roob69b182qt.apps.googleusercontent.com',
    iosBundleId: 'com.example.newhome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKArCg84SQqyZm9SY1OtmnhJpg23yyKDI',
    appId: '1:90922324784:ios:a5cda99803371eef832ef5',
    messagingSenderId: '90922324784',
    projectId: 'tubes-apb-a8acc',
    storageBucket: 'tubes-apb-a8acc.appspot.com',
    iosClientId: '90922324784-n1eo7eulgh6qvbspuj83roob69b182qt.apps.googleusercontent.com',
    iosBundleId: 'com.example.newhome',
  );
}
